### ISSUE TITLE
I am using elementary OS 5.1 Hera. I did sudo pip install git+https://github.com/techgaun/nepali-calendar-indicator, sudo pip install nepcal_applet, sudo apt install gir1.2-appindicator3-0.1 and then i run nepcal_applet from terminal. Nothing happens.

### ISSUE THREAD

**Issue by amrit9193** [techgaun/nepali-calendar-indicator#10]

**Comment by sarojbelbase** [comment]
hey it's already 2021 and it's been two years since you added this issue but can you check back again?

**Comment by techgaun** [comment]
yep I will take a look at it soon. I've not tried in a while.

**Comment by sarojbelbase** [comment]
No, I meant for OP. I'm in elementary 6 Odin and it works fine when called from the terminal minus the icon part.

**Comment by amrit9193** [comment]
> hey it's already 2021 and it's been two years since you added this issue but can you check back again?

Oh, sorry. It's been a long time and I am not using the OS anymore. 😅. Best of luck to get the icon back!!

**Comment by sarojbelbase** [comment]
Oh okay, thanks, I have submitted a PR to fix the icon. It's showing fine in my machine right now. #11

**Comment by techgaun** [comment]
closing this unless someone reports it back again. going to close for now. thanks guys
